openapi: 3.0.3
info:
  title: Swagger de API de Monster Hunter Rise Sunbreak - OpenApi 3.0
  description: Este documento tiene como fin ayudar a entender el funcionamiento de la API a los desarrolladores y colaboradores.
  contact:
    email: yassros16@gmail.com
  version: 1.0.0
servers:
  - url: localhost:3000
paths: 
  /skills:
    get:
      tags:
        - skills 
      summary: Obtener listadas todas las habilidades
      operationId: getSkills
      responses:
        '200': 
          description: Consulta exitosa
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Skill'
        '500':
          description: Error interno del servidor
  /skills/{id}:
    get:
      tags:
        - skills
      summary: Obtener una habilidad por su id
      operationId: getSkillById
      parameters:
        - name: id
          in: path
          description: ID de la habilidad deseada
          required: true
          schema: 
            type: integer
            format: int32
      responses:
        '200':
          description: Consulta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '400':
          description: ID invalido
        '404': 
          description: Habilidad no encontrada
  /skills/{nombre}/{nivel}:
    get:
      tags: 
        - skills
      summary: Obtiene el nivel de una habilidad por su nombre y nivel deseado
      operationId: getSkillByNameAndLevel
      parameters:
        - name: nombre
          in: path
          description: Nombre de la habilidade deseada
          required: true
          schema: 
            type: string
        - name: level
          in: path
          description: Nivel de la habilidad deseada
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Consulta exitosa
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/LevelSkill'

components:
  schemas:
    Skill:
      type: object
      properties:
        _id:
          type: string
          example: 644850c2e1709441f15642ea
        id:
          type: integer
          format: int32
          example: 2
        descripcion: 
          type: string
          example: Aumenta la fuerza de ataque y la afinidad cuando los mousntruos se enojan.
        nombre: 
          type: string
          example: Instigador
        nivel: 
          type: object
          properties:
            niveles:
              type: object
    LevelSkill:
      type: object
      properties:
        description:
          type: string
          example: Ataque +4 y afinidad +3% mientras esté activo
